// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmrJu-rG4n4pCon7XbujpJiF-DrdE2Op8',
    appId: '1:22459400961:web:d4407d352766069eb11100',
    messagingSenderId: '22459400961',
    projectId: 'parking-913c5',
    authDomain: 'parking-913c5.firebaseapp.com',
    storageBucket: 'parking-913c5.appspot.com',
    measurementId: 'G-0THVDE90F8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmrJu-rG4n4pCon7XbujpJiF-DrdE2Op8',
    appId: '1:22459400961:android:550c14c5aeed1c20b11100',
    messagingSenderId: '22459400961',
    projectId: 'parking-913c5',
    storageBucket: 'parking-913c5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZ5m8Urn3cxrf5qp9-poHmWfG0Bdm3ukI',
    appId: '1:22459400961:ios:0d2babd6c1c4eccdb11100',
    messagingSenderId: '22459400961',
    projectId: 'parking-913c5',
    storageBucket: 'parking-913c5.appspot.com',
    androidClientId: '22459400961-cpelfc60heb4ltt21rugn28lg7udv39q.apps.googleusercontent.com',
    iosBundleId: 'com.example.untitled1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZ5m8Urn3cxrf5qp9-poHmWfG0Bdm3ukI',
    appId: '1:22459400961:ios:0d2babd6c1c4eccdb11100',
    messagingSenderId: '22459400961',
    projectId: 'parking-913c5',
    storageBucket: 'parking-913c5.appspot.com',
    androidClientId: '22459400961-cpelfc60heb4ltt21rugn28lg7udv39q.apps.googleusercontent.com',
    iosBundleId: 'com.example.untitled1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCmrJu-rG4n4pCon7XbujpJiF-DrdE2Op8',
    appId: '1:22459400961:web:f36166edc8120479b11100',
    messagingSenderId: '22459400961',
    projectId: 'parking-913c5',
    authDomain: 'parking-913c5.firebaseapp.com',
    storageBucket: 'parking-913c5.appspot.com',
    measurementId: 'G-HYRD7KEQ8R',
  );

}